spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/businessBridge_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
